######################################################################
# Automatically generated by qmake (3.0) pon sij 25 02:56:42 2016
######################################################################

QT += core gui
QT += network
QT += widgets
TEMPLATE = app
TARGET = "Download_Manager (Source)"
INCLUDEPATH += .

# Input
HEADERS += downloader.h downloadworker.h sdownload.h
FORMS += downloader.ui
SOURCES += downloader.cpp downloadworker.cpp main.cpp sdownload.cpp
